apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-cluster-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: accessKeyID
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secretAccessKey
          sessionTokenSecretRef:
            name: aws-credentials
            key: sessionToken
