# .github/workflows/bootstrap-infra.yaml
name: Bootstrap Kubernetes Infra

on:
  workflow_dispatch:

jobs:
  bootstrap:
    name: Bootstrap EKS Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            us-east-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Atualiza kubeconfig para EKS
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name tc4-k8s-cluster

      - name: Adicionar repo External Secrets
        run: |
          helm repo add external-secrets https://charts.external-secrets.io
          helm repo update

      - name: Criar namespace external-secrets
        run: |
          kubectl create namespace external-secrets || true

      - name: Instalar External Secrets Operator
        run: |
          helm upgrade --install external-secrets external-secrets/external-secrets \
            --namespace external-secrets \
            --wait

      - name: Instalar NGINX Ingress Controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml
