name: Deploy manifests
on: 
    workflow_dispatch:
    push:
      branches:
        ["main"]
  
jobs:
  CD:
    name: Deploy no EKS (com aws-session-token)
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4.1.5

      - name: Configurar credenciais AWS (Access Key + Secret + Session Token)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            us-east-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Atualiza kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name tc4-k8s-cluster

      - name: Renderizar dinâmicamente secrets AWS
        run: |
          envsubst < templates/aws-creds-secret.yaml \
            | kubectl apply -f -

      - name: Aplicar o resto dos manifestos
        run: | 
          kubectl apply -f external-secrets/
          kubectl apply -f ingress/